name: Lint Project
on:
  push:
    branches:
      - main
      # - dev
  pull_request:

permissions:
  contents: read

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.13"

      - run: uv pip install -r requirements.txt

      - run: uv pip install ruff && ruff check .
