name: Checking
on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  Lint:
    name: Lint Project
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: "latest"

      - name: Install Python
        run: uv install python

      - name: Install Packages
        run: uv sync --all-extras --dev

      - name: Lint Project
        run: uv run ruff check .
