name: Hourly Run
on:
  workflow_dispatch:
  schedule:
    - cron: "20 * * * *"

jobs:
  Script:
    name: Script
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.12"

      - run: uv pip install -r requirements.txt

      - name: Run Script
        run: |
          uv run app.py check_rss_news
          # uv run app.py get_useful_discord_messages
          uv run app.py check_letter_grade_change
          uv run app.py check_canvas_assignments_submissions
          uv run app.py check_course_wait_list
          uv run app.py check_reddit
        env:
          LOGURU_LEVEL: "INFO"

          CANVAS_API_KEY: ${{ secrets.CANVAS_API_KEY }}

          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE_URL: ${{ secrets.OPENAI_API_BASE_URL }}
          OPENAI_API_MODEL: ${{ secrets.OPENAI_API_MODEL }}

          DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
          DISCORD_USER_TOKEN: ${{ secrets.DISCORD_USER_TOKEN }}
          DISCORD_WEBHOOK_URL_REDDIT: ${{ secrets.DISCORD_WEBHOOK_URL_REDDIT }}
          DISCORD_WEBHOOK_URL_CANVAS: ${{ secrets.DISCORD_WEBHOOK_URL_CANVAS }}
          DISCORD_WEBHOOK_URL_NEWS: ${{ secrets.DISCORD_WEBHOOK_URL_NEWS }}
          DISCORD_WEBHOOK_URL_DISCORD_SUMMARY: ${{ secrets.DISCORD_WEBHOOK_URL_DISCORD_SUMMARY }}

          USTHING_MICROSOFT_CODE_VERIFIER: ${{ secrets.USTHING_MICROSOFT_CODE_VERIFIER }}
          USTHING_MICROSOFT_REFRESH_TOKEN: ${{ secrets.USTHING_MICROSOFT_REFRESH_TOKEN }}

          MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
          MICROSOFT_CLIENT_SECRET: ${{ secrets.MICROSOFT_CLIENT_SECRET }}
          MICROSOFT_REFRESH_TOKEN: ${{ secrets.MICROSOFT_REFRESH_TOKEN }}
