name: Run
on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  Run:
    name: Run
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install Packages
        run: pip install --upgrade -r requirements.txt

      - name: Run all
        run: LOGURU_LEVEL="INFO" python app.py all
        env:
          CANVAS_API_KEY: ${{ secrets.CANVAS_API_KEY }}

          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE_URL: ${{ secrets.OPENAI_API_BASE_URL }}
          OPENAI_API_MODEL: ${{ secrets.OPENAI_API_MODEL }}

          DISCORD_WEBHOOK_URL_NEWS: ${{ secrets.DISCORD_WEBHOOK_URL_NEWS }}
          DISCORD_WEBHOOK_URL_CANVAS: ${{ secrets.DISCORD_WEBHOOK_URL_CANVAS }}
          DISCORD_WEBHOOK_URL_EMAILS: ${{ secrets.DISCORD_WEBHOOK_URL_EMAILS }}
          DISCORD_WEBHOOK_URL_DISCORD_SUMMARY: ${{ secrets.DISCORD_WEBHOOK_URL_DISCORD_SUMMARY }}

          MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
          MICROSOFT_CLIENT_SECRET: ${{ secrets.MICROSOFT_CLIENT_SECRET }}
          MICROSOFT_REFRESH_TOKEN: ${{ secrets.MICROSOFT_REFRESH_TOKEN }}
