name: Run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  Run:
    name: Run Summarize
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Packages
        run: python -m pip install -r requirements.txt

      - name: Lint Project
        run: python app.py
        env:
          IMAP_USERNAME: ${{ secrets.IMAP_USERNAME }}
          IMAP_PASSWORD: ${{ secrets.IMAP_PASSWORD }}
          IMAP_URL: ${{ secrets.IMAP_URL }}

          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE_URL: ${{ secrets.OPENAI_API_BASE_URL }}
          OPENAI_API_MODEL: ${{ secrets.OPENAI_API_MODEL }}

          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

          TSUN1031_API_KEY: ${{ secrets.TSUN1031_API_KEY }}
