name: Frequent Run
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  Script:
    name: Script
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.12"

      - run: uv pip install -r requirements.txt

      - name: Run Script
        run: uv run main.py all
        env:
          LOGURU_LEVEL: "INFO"
          CANVAS_API_KEY: ${{ secrets.CANVAS_API_KEY }}

          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE_URL: ${{ secrets.OPENAI_API_BASE_URL }}
          OPENAI_API_MODEL: ${{ secrets.OPENAI_API_MODEL }}

          DISCORD_WEBHOOK_URL_CANVAS: ${{ secrets.DISCORD_WEBHOOK_URL_CANVAS }}
          DISCORD_WEBHOOK_URL_EMAILS: ${{ secrets.DISCORD_WEBHOOK_URL_EMAILS }}
          DISCORD_WEBHOOK_URL_EMAILS_EVENTS: ${{ secrets.DISCORD_WEBHOOK_URL_EMAILS_EVENTS }}
          DISCORD_WEBHOOK_URL_EMAILS_OPPORTUNITIES: ${{ secrets.DISCORD_WEBHOOK_URL_EMAILS_OPPORTUNITIES }}
          
          MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
          MICROSOFT_CLIENT_SECRET: ${{ secrets.MICROSOFT_CLIENT_SECRET }}
          MICROSOFT_REFRESH_TOKEN: ${{ secrets.MICROSOFT_REFRESH_TOKEN }}
