name: Automated Tasks
on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  tasks:
    name: Tasks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.12"

      - run: uv pip install -r requirements.txt

      - name: Run Script
        run: uv run main.py
        env:
          LOGURU_LEVEL: "INFO"

          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE_URL: ${{ secrets.OPENAI_API_BASE_URL }}
          OPENAI_API_MODEL: ${{ secrets.OPENAI_API_MODEL }}

          DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
          DISCORD_WEBHOOK_EMAIL_INFO: ${{ secrets.DISCORD_WEBHOOK_EMAIL_INFO }}
          DISCORD_WEBHOOK_EMAIL_EVENT: ${{ secrets.DISCORD_WEBHOOK_EMAIL_EVENT }}
          DISCORD_WEBHOOK_EMAIL_PROGRAM: ${{ secrets.DISCORD_WEBHOOK_EMAIL_PROGRAM }}

          MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
          MICROSOFT_CLIENT_SECRET: ${{ secrets.MICROSOFT_CLIENT_SECRET }}
          MICROSOFT_REFRESH_TOKEN: ${{ secrets.MICROSOFT_REFRESH_TOKEN }}
