name: Run
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  Run:
    name: Run Summarize
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: "latest"

      - name: Install Python
        run: uv install python

      - name: Install Packages
        run: uv sync --all-extras --dev

      - name: Run
        run: uv python app.py
        env:
          IMAP_USERNAME: ${{ secrets.IMAP_USERNAME }}
          IMAP_PASSWORD: ${{ secrets.IMAP_PASSWORD }}
          IMAP_URL: ${{ secrets.IMAP_URL }}

          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE_URL: ${{ secrets.OPENAI_API_BASE_URL }}
          OPENAI_API_MODEL: ${{ secrets.OPENAI_API_MODEL }}

          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

          REDIS_CONNECTION_STRING: ${{ secrets.REDIS_CONNECTION_STRING }}
